In [ ]:
#Workflow Of Sci-Kit Learn
'''
1) Setting up the data
2) Creating the Model
3) Training the Model
4) Prediction
'''

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Importing LogisticRegression Model
#0 - Ham email
#1 - Spam email
from sklearn.linear_model import LogisticRegression

In [ ]:
#Importing accuracy score function
from sklearn.metrics import accuracy_score

In [ ]:
#Importing train test split function
from sklearn.model_selection import train_test_split

In [ ]:
#To convert all the strings formats into numeric
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#Importing the dataset
raw_mail_data = pd.read_csv('mail_data.csv')
raw_mail_data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
#Replacing all the null values with null string
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)), '')
mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
#Printing the 5 rows
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#Checking the rows and columns of the dataset
mail_data.shape

(5572, 2)

**LABEL ENCODING**

In [ ]:
#Label spam email as 0 and ham email as 1
mail_data['Category'] == 'spam'
#mail_data.iloc[0:3, 0]
#mail_data.loc[0:3, 'Category']

0       False
1       False
2        True
3       False
4       False
        ...
5567     True
5568    False
5569    False
5570    False
5571    False
Name: Category, Length: 5572, dtype: bool

In [ ]:
mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0

In [ ]:
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [ ]:
mail_data

     Category                                            Message
0           1  Go until jurong point, crazy.. Available only ...
1           1                      Ok lar... Joking wif u oni...
2           0  Free entry in 2 a wkly comp to win FA Cup fina...
3           1  U dun say so early hor... U c already then say...
4           1  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567        0  This is the 2nd time we have tried 2 contact u...
5568        1               Will ü b going to esplanade fr home?
5569        1  Pity, * was in mood for that. So...any other s...
5570        1  The guy did some bitching but I acted like i'd...
5571        1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
#Find the total number of ham email and spam email
mail_data['Category'].value_counts()

1    4825
0     747
Name: Category, dtype: int64

In [ ]:
#Separating the data as texts and label
X = mail_data['Message'] #Input Feature
Y = mail_data['Category'] #Label

In [ ]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [ ]:
#Splitting the data into training data and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)
print(X.shape, X_train.shape, Y_test.shape)

(5572,) (4457,) (1115,)

In [ ]:
#Transforming the text data to feature vectors that can be used as input to the logistic regression
feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english', lowercase = True)

In [ ]:
X_train_num  = feature_extraction.fit_transform(X_train)
X_test_num = feature_extraction.transform(X_test)

In [ ]:
#Convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

**Training the data**

In [ ]:
model = LogisticRegression()

In [ ]:
#Training the Logistic Regression model with the training data
model.fit(X_train_num, Y_train)

LogisticRegression()

In [ ]:
#Evaluating the Trained Model
X_train_prediction = model.predict(X_train_num)
#Finding the accuracy on training data
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print("Accuracy Score of training data", training_data_accuracy)

Accuracy Score of training data 0.9683643706529056

In [ ]:
X_test_prediction = model.predict(X_test_num)
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print("Accuracy Score of testing data", testing_data_accuracy)

Accuracy Score of testing data 0.9524663677130045

In [ ]:
#Building a predictive system
input_mail = ['Free Free Free You have won a lottery']
input_mail_num = feature_extraction.transform(input_mail)

In [ ]:
#Making Prediction
prediction = model.predict(input_mail_num)
if prediction[0] == 1:
  print('Ham Email')
else:
  print('Spam Email')

Spam Email