In [ ]:
import pandas as pd
df = pd.read_csv('USA_cars_datasets.csv')
df

,Index,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,Unnamed: 13,year.1,Frequency
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,NaN,2019.0,892.0
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,NaN,2018.0,395.0
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,NaN,2017.0,377.0
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,NaN,2016.0,203.0
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,NaN,2015.0,196.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left,NaN,NaN,NaN
2495,2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left,NaN,NaN,NaN
2496,2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left,NaN,NaN,NaN
2497,2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left,NaN,NaN,NaN
2498,2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         2499 non-null   int64
 1   price         2499 non-null   int64
 2   brand         2499 non-null   object
 3   model         2499 non-null   object
 4   year          2499 non-null   int64
 5   title_status  2499 non-null   object
 6   mileage       2499 non-null   int64
 7   color         2499 non-null   object
 8   vin           2499 non-null   object
 9   lot           2499 non-null   int64
 10  state         2499 non-null   object
 11  country       2499 non-null   object
 12  condition     2499 non-null   object
 13  Unnamed: 13   0 non-null      float64
 14  year.1        30 non-null     float64
 15  Frequency     30 non-null     float64
dtypes: float64(3), int64(5), object(8)
memory usage: 312.5+ KB

In [ ]:
#Removing 13th column
df.drop('Unnamed: 13', axis = 1, inplace = True)
df

,Index,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,year.1,Frequency
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,2019.0,892.0
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,2018.0,395.0
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,2017.0,377.0
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,2016.0,203.0
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,2015.0,196.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left,NaN,NaN
2495,2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left,NaN,NaN
2496,2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left,NaN,NaN
2497,2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left,NaN,NaN
2498,2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left,NaN,NaN

In [ ]:
cond = pd.unique(df['state'])
len(cond)

44

In [ ]:
cond = pd.unique(df['brand'])
len(cond)

28

In [ ]:
#(df['state'] == 'new jersey').sum()
df[df['state'] == 'new jersey']['state'].count()

87

In [ ]:
df.groupby(by = 'brand')['price'].mean().sort_values()

brand
peterbilt            400.000000
jaguar              2800.000000
heartland           2966.000000
hyundai             5203.200000
honda               6127.500000
toyota              6300.000000
acura               7266.666667
mazda               8000.000000
gmc                10657.380952
jeep               10933.833333
ram                11050.000000
kia                11123.846154
nissan             12065.820513
infiniti           13098.333333
chrysler           13686.111111
audi               13981.250000
dodge              17781.988426
lincoln            18150.000000
chevrolet          18669.952862
buick              19715.769231
ford               21666.888259
cadillac           24941.000000
bmw                26397.058824
mercedes-benz      28704.000000
land               28900.000000
maserati           30300.000000
lexus              33220.000000
harley-davidson    54680.000000
Name: price, dtype: float64

In [ ]:
from datetime import datetime
current_year = datetime.now().year
df['Vehicle Age'] = current_year - df['year']
df

,Index,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,year.1,Frequency,Vehicle Age
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,2019.0,892.0,15
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,2018.0,395.0,12
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,2017.0,377.0,5
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,2016.0,203.0,9
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,2015.0,196.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left,NaN,NaN,4
2495,2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left,NaN,NaN,5
2496,2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left,NaN,NaN,5
2497,2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left,NaN,NaN,5
2498,2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left,NaN,NaN,5

In [ ]:
cond = (df['year'] == 2008)
df[cond]['year'].count()
#df[df['year'] == 2008]

18

In [ ]:
df[(df['year'] == 2008) & (df['color'].isin(['red','blue','yellow']))]

,Index,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,year.1,Frequency,Vehicle Age
301,301,50,chevrolet,door,2008,salvage insurance,172102,blue,1g1al58f787159241,167650632,texas,usa,18 hours left,NaN,NaN,15
328,328,2960,chrysler,van,2008,clean vehicle,164048,red,2a8hr54px8r787529,167660587,florida,usa,23 hours left,NaN,NaN,15
430,430,450,chevrolet,coupe,2008,salvage insurance,123515,yellow,1g1al18f587145539,167650407,minnesota,usa,2 days left,NaN,NaN,15
443,443,0,chevrolet,coupe,2008,salvage insurance,270080,yellow,1g1al18f187245041,167650422,illinois,usa,17 hours left,NaN,NaN,15
518,518,50,chevrolet,door,2008,salvage insurance,172102,blue,1g1al58f787159241,167650632,texas,usa,17 hours left,NaN,NaN,15
522,522,0,ford,door,2008,salvage insurance,145483,red,1fmcu03128kc80487,167357813,oklahoma,usa,17 hours left,NaN,NaN,15

In [ ]:
state = (df[df['state'] == 'new jersey'])
state['color'].value_counts()

white                                      17
gray                                       15
black                                      14
silver                                      8
red                                         6
blue                                        5
magnetic metallic                           4
billet silver metallic clearcoat            2
oxford white                                2
no_color                                    2
ingot silver metallic                       2
orange                                      1
guard                                       1
kona blue metallic                          1
royal crimson metallic tinted clearcoat     1
color:                                      1
shadow black                                1
ruby red metallic tinted clearcoat          1
triple yellow tri-coat                      1
bright white clearcoat                      1
white platinum tri-coat metallic            1
Name: color, dtype: int64

In [ ]:
df[df['color'] == 'yellow']['state'].value_counts()
#yellow_cars = df[df['color'] == 'yellow']
#yellow_cars.groupby(by = 'state')['state'].count()

michigan      3
florida       2
california    2
minnesota     1
illinois      1
Name: state, dtype: int64

In [ ]:
df[(df['brand'].isin(['toyota', 'ford', 'nissan'])) & (df['color'].isin(['black', 'silver']))]['state'].value_counts()

pennsylvania      80
florida           61
minnesota         45
california        33
illinois          32
michigan          31
texas             28
virginia          23
nevada            20
new jersey        17
north carolina    16
south carolina    15
new york          13
tennessee         10
oklahoma           9
oregon             9
georgia            8
wisconsin          8
arizona            7
massachusetts      7
connecticut        7
mississippi        6
alabama            6
missouri           6
ohio               5
louisiana          4
colorado           4
west virginia      3
indiana            3
new hampshire      1
utah               1
arkansas           1
kansas             1
maryland           1
Name: state, dtype: int64

In [ ]:
#Find the count of all colors in all states and sort them according to the highest number to lowest.
df.groupby(by = 'state')['color'].value_counts().sort_values(ascending = False)

state         color
texas         white                                      93
pennsylvania  black                                      89
              white                                      84
florida       black                                      64
              white                                      59
                                                         ..
new jersey    kona blue metallic                          1
              orange                                      1
              royal crimson metallic tinted clearcoat     1
              ruby red metallic tinted clearcoat          1
wyoming       maroon                                      1
Name: color, Length: 342, dtype: int64

In [ ]:
#Filter the entire data where price is greater than $25000
df[df['price'] > 25000]

,Index,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,year.1,Frequency,Vehicle Age
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,2015.0,196.0,5
12,12,31900,chevrolet,1500,2018,clean vehicle,22909,black,3gcukrec0jg176059,167763273,tennessee,usa,22 hours left,2009.0,11.0,5
19,19,38100,ford,door,2013,clean vehicle,54380,gray,1ft8w3dt5deb68569,167753923,virginia,usa,22 hours left,2000.0,4.0,10
32,32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left,NaN,NaN,50
42,42,30500,chevrolet,1500,2018,clean vehicle,30442,red,3gcukrec4jg204915,167763393,tennessee,usa,22 hours left,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2324,2324,28000,nissan,armada,2018,clean vehicle,29554,gray,jn8ay2nc4j9558303,167750230,pennsylvania,usa,3 days left,NaN,NaN,5
2331,2331,26800,nissan,titan,2018,clean vehicle,33605,white,1n6aa1ej0jn540880,167751557,new mexico,usa,21 hours left,NaN,NaN,5
2375,2375,36300,nissan,xd,2017,clean vehicle,16224,white,1n6ba1f46hn535299,167753308,virginia,usa,21 hours left,NaN,NaN,6
2442,2442,28100,nissan,pathfinder,2018,clean vehicle,8889,silver,5n1dr2mm3jc651473,167761668,illinois,usa,21 hours left,NaN,NaN,5
2473,2473,30100,nissan,titan,2019,clean vehicle,30599,black,1n6aa1e56kn519701,167718010,north carolina,usa,21 hours left,NaN,NaN,4

In [ ]:
#Find unique values of title_status column and count the number of clean vehicle
#df['title_status'].value_counts()
cond1 = pd.unique(df['title_status'])
cond2 = df[df['title_status'] == 'clean vehicle']
cond2['title_status'].count()

2336